= la la'uma'arbi'i
Wei Tang <wei@that.world>

[meta=description]
ni'o ti noi lisri cu srana lo tcadu po'u la la'uma'arbi'i .i ty noi ca'arxe cu
zvati lo'e stuzi pe lo terdi .i le sunsicyjudri .e le bernanjudri .e le gugde pe
ty cu na srana lo lisri .i ko poi se tcidu cu tolju'i lo ti tilvi'a (to ti tcadu
noi mi zbasu ke'a ne'i lo kelci'e po'u la'o gy. Cities Skylines gy.

== trene nu klama fanta
detri fa 2017-06-27 00:00:00 +0800

ni’o pa barda trene nu klama fanta cu fasnu ne’i la la’uma’arbi’i .i so’e trene
cu sisti ki’u ti .i lo cnino dargu platu cu se gasnu

== la kubli tcadu
detri fa 2017-06-27 00:00:00 +0800

ni’o la kubli tcadu po’u la’o gy. Hexagon City gy. cu tcadu fi la la’uma’arbi’i
.i ro dargu pe ne’i ti cu kubli fe li xa .i so’e dargu ne’i ti cu dargu fi pa
farna

== pemni nu klama
detri fa 2017-06-26 00:00:00 +0800

ni’o la stuz .e la pelas so’eroi klama lo kinrxanime jarco stuzi .a lo sagdraci
.i la stuz cu da’i denpa lo tcana pe la’o py. Hexagon City py .i xai cu ba klama
fu lo trene fe la’o py. Lakevalley North py poi stuzi lo sagdraci stuzi .e lo
esporte stuzi

== nuntumdesku
detri fa 2017-06-26 00:00:00 +0800

ni’o pa nuntumdesku cu fasnu ne’i la la’uma’arbi’i .i zanselfu’a lo nu la stuze
.e ‘a pelas to’e corgau .i la stuz cu zdani lo jibni lo midju pe lo nuntumdesku
.i sy pu viska lo ralju bilga xotli cu binxo lo temfesti