= le ni'orai se karni
Wei Tang <wei@that.world>

[meta=description]
ni'o mi ciska lo se karni .i di'e le ni'orai

== termu'eske ctuca
detri fa 2015-11-10 00:00:00 +0800

ni’o la xaimon cu jungau mi tu’a lo termu’eske ctuca pe ca lo nu verba .i cy cu
xamsku tu’a lo pafmamta .i xy cu morji lo nu cy ca lo nu ctuca cu cusku lo du’u
lo mi pafmamta cu morsi .i ca lo nu cy klasazri gi’e tolcfagau ki’u lo
fletrogusmi’i ku cy viska lo mlatu .i cy pilno lo gusni lo nu ci’erkei .i cy
cusku lo du’u ca lo nu verba ku cy pilno lo simsa gusni lo nu ci’erkei lo
pafmamta

ni’o xy kakne so’ida .i mi suzroi djuno lo du’u da memcre zmadu vi lo minje

== tarci
detri fa 2015-11-09 00:00:00 +0800

ni’o lo tarci cu melbi ca lo nicte .i mi’a zgana lo tarci vi lo brablo

== bangrtai
detri fa 2015-11-08 00:00:00 +0800

ni’o cinri fa lo du’u lo bangrtai cu na pilno lo te pandi

== ka remna
detri fa 2015-11-07 00:00:00 +0800

lu na curmi sei la .haimon. cu cusku .i da na jmive secau lo ka prami li’u .i
doi .haimon. mi pacna lo nu do drani

== plinyxabykoi
detri fa 2015-11-06 00:00:00 +0800

ni’o mi djuno lo du’u ca lo cabdei ku mi’a cu pagre lo plinyxabykoi .iseki’ubo
mi reisku fi lo nixli fe lo du’u ca ma mi’a cu pagre .i lu .ue mi’a pu pagre ca
lo cerni sei lo nixli cu cusku .i do ca lo cerni mo li’u .i lu mi sipna sei mi
cusku li’u .i li .uu sei lo nixli cu cusku li’u

== tepsla
detri fa 2015-11-05 00:00:00 +0800

ni’o lu ta’i ma do selci lo tepsla vi lo mergu’e sei mi reisku li’u .i lu tersla
sei spusku li’u .i lu xu .ue po’o dansu tersla li’u .i lu go’i li’u

== lo nu krixa
detri fa 2015-11-04 00:00:00 +0800

ni’o le te terctu cu cpedu lo nu ro mi’a cu krixa ro da poi raktu ca lo nu mi’a
litru vi lo gugdesunu .i lo nu krixa cu ranji ca’o lo mentu be li re

== la'o gy. Nacirema gy.
detri fa 2015-11-03 00:00:00 +0800

ni’o le te terctu cu dunda mi’a lo lisri .i ly se srana lo prenu pe la’o gy.
Nacirema gy .i ba lo nu tcidu ku mi’a cusku lo du’u la’o gy. Nacirema gy. cu
drata gi’e cizra .iku’i ro lo lisri cu se srana mi’a .i la’o gy. Nacirema gy. cu
fatne la’o gy. American gy.

== nandu
detri fa 2015-11-01 00:00:00 +0800

[quote]
[%hardbreaks]
ni’o ro da noi
zasti ne’i lo munje
cu nandu
.iganai do prami
gi lo zasti cu frili

lo lijda prenu poi zvati la’o gy. Keur Massar gy. cu cusku da’e

== lo se dikle'i
detri fa 2015-11-01 00:00:00 +0800

ni’o badri lo nu fau lo nu mi’a jinvi lo nu mi’a dukse te ca’irdi’a ku lo vecnu
cu dikle’i lo fepni be li reno .i fy cu mleca lo nacmecrai se dikle’i pe vi lo
merko

== lo braxamsi boxna
detri fa 2015-11-01 00:00:00 +0800

ni’o ba lo nu lo bloti cu marce fi lo braxamsi sefta ku lo sy boxna cu drata lo
boxna pe lo nu na go’i .i lo sy boxna cu ranti .i lo drata cu kinli

== lo nu se sorprekarce
detri fa 2015-10-31 00:00:00 +0800

ni’o cinri fa lo sorprekarce pe vi la’o gy. Dakar gy .i viku blanu sorprekarce
gi’e blabi sorprekarce gi’e ge blanu gi blabi sorprekarce gi’e pelxu sorprekarce
co dukse selja’i .i na zasti fa lo cartu be lo sorprekarce .iji’a lo
sorprekarcytcana dagysni cu na frili se jimpe .i ro da cu cinri gasnu lo nu se
sorprekarce noi mi ca lo cabdei cu lifri

ni’o pamai se zukte fa lo nu zvafa’i lo sorprekarcytcana .i mi klama lo remgunma
zarci .i lo clani depstu cu simsa lo sorprekarcytcana .iku’i na dagysni .i mi
retsku lo prenu poi denpa lu xu viku lo sorprekarce poi tcita lo pamai cu se
tcana li’u .i py na se bangu lo glibau .iseki’ubo mi pilno lo mi xance lo nu
xanle’u la’e li pa .i py jimpe .i py jinvi cusku .i mi denpa

ni’o lo zarci cu ge remgunma gi savru ckaji .i mi denpa ba lo cacra be li pimu
.i na sorprekarce co tcita la’e li pa .i mi cliva .i mi klama lo zarci
mo’ica’uku .i mi jinvi lo du’u mi fliba .iku’i mi penmi lo karce

ni’o lo nu klasazri cu masno .iku’i cinri

== lo xekri
detri fa 2015-10-30 00:00:00 +0800

ni’o la brandas cu pa cusku lo cinri lisri ca lo jarco .i by briko .i lo by
skapi se skari cu manku .i by cu jai se jinvi fa by fe lo merko fai lo bu’u by
xekri .iku’i vi lo lazyzda by na cu jai se jinvi fai lo bu’u by xekri .i ti
midju manku .i lo gugdesudu prenu cu xekri

== lo buklolgai
detri fa 2015-10-29 00:00:00 +0800

ni’o pa lo nixli cu jungau mi lo cinri lifri .i vi la’o gy. Marrakech gy. ny cu
cadzu lo klaji .i lo vacnu cu reisku lo du’u xukau ny djica lo nu klama lo
zaisle be fo vy .i ny cu na xamgu kakne lo nu fitytoltu’i .iseki’ubo ny klama .i
vy reisku lo du’u xukau ny djica lo nu terve’u lo buklolgai .i ny cu na xamgu
kakne lo fitytoltu’i .iseki’ubo ny selve’u sepi’o so’i lo jdini .i ki’u lo nu
pilno so’i jdini ku ny na nelci lo bi’unai buklolgai .i ny tikpa by ca ro lo
djedi

== la pinpon
detri fa 2015-10-28 00:00:00 +0800

ni’o mi .e la’o zy. Haimeng zy. bolkei la pinpon .i la’e di’u cu paroi
xadypalmu’u vi lo brablo .i mi nelci lo se cinmo pe lo nu bolkei .i lo brablo cu
desku .i lo xamsi cu blanu .i melbi

== lo temci
detri fa 2015-10-27 00:00:00 +0800

ni’o mi cfasanji lo nu mi tolcando ca’oze’u .i lo temci na banzu .i lo ckule
gunka cu dukse .i ju’ocu’i .ei mulgau lo nu mi .ei mulno ca’o lo djedi

== lo cerni
detri fa 2015-10-26 00:00:00 +0800

ni’o melbi fa lo cerni be fi la’o gy. Fez gy .i lo janbe pe vi lo tcadu cu cladu
skumi’e lo muslo prenu lo nu jdaselsku .i funca fa lo nu mi za’o cikybi’o .i
la’e di’u se djecacrytcika li xa ca lo cerni .i lo sorprekarce cu xa’o tolpo’u
.i lo prenu cu xa’o cadzu ja carvrama’e .i lo karce cu xa’o klama vi lo dargu .i
lo zdadi’u cu melbi .i pluja pluta

== lo nu lerci
detri fa 2015-10-25 00:00:00 +0800

ni’o mi reroi lerci klama lo trene .i lo nu djuno lo nitcu temci cu na frili
.iki’ubo ti steba

== lo verba se zvati
detri fa 2015-10-24 00:00:00 +0800

ni’o mi klama lo zdani be lo diklo prenu .i lo selvi’e cu sabji lo cidja mi’a .i
mi cfaga’e lo du’u lo nomoi cidja cu simsa lo nomoi cidja pe du’u lo mi verba se
zvati

ni’o lo selvi’e cu kulmu’o puviku .iku’i mi’a na tavla so’i lo smuni culno

== lo lutnilcla
detri fa 2015-10-24 00:00:00 +0800

ni’o mi cadzu vi lo nenri tcadu be la’o gy. Marrakech gy .i mi viska lo purdi
sepi’o lo farna pelji .i mi cipcta sepi’o lo mi selbeifonxa .i zvati clani metre
li re ki’o .i mi jinvi lo du’u ti zvati clani tordu .iseki’ubo mi jdice lo du’u
mi cadzu klama lo purdi

ni’oku’i mi pilno lo cacra .i mi djuno lo du’u mi dubji’isre lo lutnilcla

== lo verba se zvati
detri fa 2015-10-23 00:00:00 +0800

ni’o ca lo remoi djedi mi zvati lo zarci pe vi la’o gy. Marrakech gy .i ro pluta
cu pluja se farna gunka .i lo zaisle cu fe’eroroi stuzi .i lo prenu cu fe’eroroi
klama .iku’i mi cinmo lo ka zvati tu’a lo mi verba .iki’ubo ca lo nu mi verba mi
nelci lo nu klama lo tai zarci .iji’a lo nixli noi di’i zvati lo gugdesugu cu
cusku lo du’u cinmo lo simsa

== lo bangu
detri fa 2015-10-22 00:00:00 +0800

ni’o mi pare’u klama lo gugde poi vi ke’a so’i prenu na se bangu lo glibau
.iseki’ubo lo nu tavla cu nandu .iku’i re lo se zukte cu pu snada .i corci .i
cisma

ni’o xagrai se zukte fa lo nu cilre lo vi bangu

== lo penmi prenu
detri fa 2015-10-21 00:00:00 +0800

ni’o capyju’i lo nu pendo gasnu lo mi penmi .i na krinu fa lo nu mi na nelci lo
nu pendo .iku’i krinu lo nu ronai da cu xamgu pendo .i mi pendo gasnu lo so’i
prenu ca lo nu mi zvati la’o gy. Hacker School gy .i mi .e py selfai so’i da noi
ckini lo skami .iku’i mi na selfai so’i ca lo nu mi cmizu’e la’o gy. Semester at
Sea gy .iseki’ubo mi na pendo so’i da viku

== cargau lo junla lo ni cacra lo purci
detri fa 2015-10-20 00:00:00 +0800

ni’o mi’a vi lo barblo cu cargau lo junla lo ni cacra lo purci .i mi cpacu lo
ziljmina cacra .i mi’a su’o re roi cargau .ije lo barblo prenu cu pilno lo cacra
lo nu cilre gi’a ciska gi’a mencti lo skina .i mi’a gleki gi’e se sidju cy lo nu
dragau lo mi’a temci cretro

ni’oku’i fau lo nu mi zanfri cy kei mi pensi cusku lu xu mi cirko lo mulno djedi
ca lo temci li’u

== lo sanga
detri fa 2015-10-19 00:00:00 +0800

ni’o mi’a cu klama la’o gy. Monsterrat gy .i lo xismalsi cu vi zvati .i lo verba
cu sanga ne’iku ca lo dormidju .i melbi

== carvrama'e
detri fa 2015-10-19 00:00:00 +0800

ni’o detri jbini li pi’epi’e 15 .e li pi’epi’e 18 fau lo nu mi carvrama’e .i mi
kansa lo re nixli poi mi penmi ke’a bu’u lo brablo .i lo se penmi cu xamgu kakne
lo nu jikca .ije mi mutce co cilre lo nu ta’i so’o makau mi jikca ca lo nu mi
litru

ni’o ca lo pamoi djedi mi .e lo re kansa cu klama lo carvrama’e zaisle bu’u la’o
gy. Valencia gy .i ca lo su’omoi kei mi .e ky cu se spusku lu xu do birti li’u
.i lo zaisle prenu cu na krici lo du’u lo nanla .e re lo nixli cu kakne lo nu
carvrama’e klama la’o gy. Barcelona gy. la’o gy. Valencia gy.

ni’o ca lo pamoi lecydo’i mi reroi farcri .i mi na joska’e lo kibro .iseki’ubo
mi cuxna lo farna ta’i lo cunso .iku’i mi snada co troci lo nu klama lo xamsi
korbi .i ti melbi

ni’o ca lo remoi djedi mi gleki lo du’u mi na nitcu lo nu platu lo farna .ije mi
cinri tavla lo re nixli lo nu jikca .i mi ny cu mo’u tugni lo du’u mi .ei cilre
lo du’u ta’i makau cu mi jikca

ni’o ca lo cimoi djedi mi po’o klama .i mi facki lo mivmu’e panka poi bu’u ke’a
mi kakne carvrama’e .i mi kansa no da .iseki’ubo mi gleki

ni’oku’i mi fi ny danba ca lo cimoi nicte .i ki’u lo nu mi na ponse rau jdini .i
mi carvrama’e za’u re’u ca lo nicte .i ti ckape je cinri

== lo cikre relxilma'e prenu
detri fa 2015-10-18 00:00:00 +0800

ni’o mi se raktu lo nu mrilu lo mi relxilma’e lo krasi .i mi pamoi cusku lo du’u
makau cu se nitcu .iku’i lo vecnu na jimpe .i mi klama lo drata zaisle .i mi
penmi lo cikre relxilma’e prenu .i py dafyfa’i ca lo clatei .i kargu .i pedypa’i

== lo nu na penmi
detri fa 2015-10-17 00:00:00 +0800

ni’o mi carvrama’e klama lo mivmu’e noi na penmi lo drata prenu .i my smaji .i
my melbi .i mi carvrama’e klama ca’o lo cacre be li re .i lo nu na penmi cu
xamgu lifri

== lo nu girzu litru
detri fa 2015-10-16 00:00:00 +0800

ni’o lo nu girzu litru cu na frili .i lo te jansu cu cfari .i lo toltu’i cu
cfari .i mi nelci lo nu girzu litru penmi lo skami prenu

== lu xu do birti li'u
detri fa 2015-10-15 00:00:00 +0800

ni’o mi’a cu ca facki lo zaisle poi vi ke’a terve’u lo relxilma’e poi sepi’o
ke’a klama fa la’o gy. Valencia gy. la’o gy. Barcelona gy .i mi’a cusku lo se
pacna pa lo zaisle .i zy spuda cusku lu xu do birti li’u

== lo nu fizbu
detri fa 2015-10-14 00:00:00 +0800

ni’o la fionas cu cusku lo du’u ti fizbu lo nu carvrama’e ca lo bavlamdei .iku’i
xanka lo jifxu’a cu cfari

== noda
detri fa 2015-10-13 00:00:00 +0800

ni’o noda cu cfari ca lo cabdei .i lo jmive cu na roroi cinri

== la bisli
detri fa 2015-10-12 00:00:00 +0800

ni’o vi lo brablo ku mi viska lo skina pe la bisli .i mi puze viska sy .iku’i lo
nu remoi viska cu drata

== lo pipno
detri fa 2015-10-11 00:00:00 +0800

ni’o ca lo cabdei lo fasnu cu cfari .i fy ca’icpe lo nu lo te girzu cu zgipli lo
pipno .i so’i lo te girzu na kakne lo nu zgipli lo pipno .i cinri fa lo nu tirna
lo zgike poi lo te girzu cu finti

== lo fliba
detri fa 2015-10-10 00:00:00 +0800

ni’o lo fliba cu fliba .iku’i do cilre fo lo fliba pe vi la’o gy. Greece gy.

== lo zdacau
detri fa 2015-10-09 00:00:00 +0800

ni’o lo prenu poi pa zdacau cu gidva mi’a lo nu klama lo stuzi pe lo zdacau .i
mi’a retsku lo du’u jinvi makau pe lo zdacau poi cpedu lo jdini .a lo cidja .i
py dafsku lo du’u zy na xamgu zdacau gi’e mi’a .ei na dunda zy lo jdini .a lo
cidja ki’u lo nu la’e di’u mukti lo nu zy ba zdacau je cpedu

== lo zairsnucu'u prenu
detri fa 2015-10-08 00:00:00 +0800

ni’o mi tavla lo zairsnucu’u prenu .i mi reisku lo du’u py nelci lo nu lo skami
prenu cu mo .i py spuda lu zmadu co jungau li’u

== lo tcepru bangu
detri fa 2015-10-07 00:00:00 +0800

ni’o mi penmi lo tcepru bangu vi la’o gy. National Archlogical Museum gy .i lo
bi’unai tcepru bangu cu simsa lo jungo tcepru bangu

== lo sutra kibro
detri fa 2015-10-06 00:00:00 +0800

ni’o mi facki lo sutra kibro ca lo cabdei .i mi cfasanji lo du’u lo sutra kibro
cu vajni .iku’i mi na so’i zei gasnu

== lo litru jibri
detri fa 2015-10-05 00:00:00 +0800

ni’o mi tirna lo nu re lo ve balcu’e cu tavla fi lo litru jibri .i cinri fa lo
nu do kakne lo nu cilre ti sepi’o lo nonseldi’a

== zvijonse lo kibro
detri fa 2015-10-04 00:00:00 +0800

ni’o mi’a na kakne lo nu jonse lo culno kibro vi lo brablo .iku’i cumki fa lo nu
zvijonse lo kibro .i mi’a kakne lo nu jonse la uikipedias .i la uikipedias cu se
pilno fi lo ve cusku .i cusku’i lo vlapoi pe vi la uikipedias .i jonse lo kibro

== lo nicte sorprekarce
detri fa 2015-10-03 00:00:00 +0800

ni’o ganai mi capyju’i zgana ca lo nu mi klama fu lo nicte sorprekarce gi mi
facki lo cinri .i ca lo cerni ku mi facki lo pendo cu zvati lo mintu sorprekarce

== lo nu cadzu vi lo cmana
detri fa 2015-10-02 00:00:00 +0800

ni’o mi nelci lo nu cadzu vi lo cmana .i zmadu lo nu cadzu .i fau lo nu cadzu vi
lo cmana ku pensi fa mi .i mi so’eroi pensi lo pijyske .i mi mo .i mi klama fi
ma .i mi klama fe ma .i mi nelci lo nu cadzu vi lo cmana

== lo nu xalbebna
detri fa 2015-09-30 00:00:00 +0800

ni’o mi xalbebna ca lo cabdei .i mi zvati lo cmalu daplu .ije citka lo
dormijysai gi’e kansa lo pendo .i mi citka lo so’u xalka .i mi xalbebna .i mi na
kakne lo nu skicu lo cnirango be lo nu mi xalbebna

== lo dijypanka
detri fa 2015-09-29 00:00:00 +0800

ni’o cinri fa lo nu zutse lo dijypanka gi’e viska lo prenu .e lo dacti vi la’o
gy. Bell Tower gy .i mi viska so’i lo prenu poi terxra .i lo prenu cu citka lo
bisyladru .i lo verba cu bajra .i lo verba cu nitkla fo lo serti .i lo verba cu
vobmipri ci’erkei .i mi viska lo mi pendo poi rinsa gi’a na rinsa .i ca lo suksa
lo serti poi mi zutse cu tisna lo prenu .i kacma co ralte fa lo prenu .i
victerlu’i jajgau prenu .i prenu co reisku lo farna .i ca lo suksa ku re lo
ninmu cu masno gi’e rinsa

== lo pavnid skina ca'o lo nanca
detri fa 2015-09-27 00:00:00 +0800

ni’o lo prenu cu zbasu lo pavnid skina ca’o lo nanca .i ti cinri gi’e melbi

== lo du'u xukau lo lijda cu sarcu
detri fa 2015-09-26 00:00:00 +0800

ni’o mi’a dausnu lo du’u xukau lo lijda cu sarcu .i cinri fa lo se lijda cu
da’asnu kambandu lo ly lijda

== lo te platu litru
detri fa 2015-09-25 00:00:00 +0800

ni’o mi penmi lo drata ve balcu’e ca lo dormijysai temci .i djugau mi lo du’u by
nelci lo nu vitke lo te platu litru .i cinri ki’u lo nu mi nelci lo nu nonkansa
litru gi’e by cu na xamgu kakne lo nu tavla ku co simsa mi

== lo romoi djedi pe vi lo blotcana
detri fa 2015-09-24 00:00:00 +0800

ni’o cabdei fa lo romoi djedi pe vi lo blotcana .i ti simsa lo se tcena zeldei
nicte .i do ciska lo pu lifri .i do pensi .i xamgu

== lo pedypa'i prenu
detri fa 2015-09-23 00:00:00 +0800

ni’o mi penmi lo pedypa’i prenu vi la’o gy. Naples gy .i ca lo nicte mi puzi
darca la’o gy. Naples gy .i mi na djuno lo farna .i fau lo nu mi viska lo farna
pelji ku lo prenu cu reisku lo du’u fe makau fa mi klama .i py sabji lo farna
.iku’i mi na facki lo farna ze’abaku .i mi reisku lo drata prenu .i py klama lo
xotli gi’e dunda mi lo farna pelji

ni’o xamgu fa lo pedypa’i prenu

== la nunzi'e prexra
detri fa 2015-09-23 00:00:00 +0800

ni’o vi la’o gy. San Marino gy. zvati fa la nunzi’e prexra .i drata fa la
nunzi’e prexra lo prexra pe vi la’o gy. New York gy .i py pe vi la’o gy. San
Marino gy. cu tolci’o zmadu .i lo py pritu jamfu cu crane zmadu .i lo py pritu
xance cu ralte lo kilga’axa’i .i melbi

== lo pedypa'i prenu
detri fa 2015-09-22 00:00:00 +0800

ni’o mi farna facki vi la’o gy. San Marino gy .i mi pemni lo pedypa’i prenu poi
cusku lu xamgu funca li’u

== citno dukse fi lo nu litru
detri fa 2015-09-21 00:00:00 +0800

ni’o mi penmi so’i lo tolci’o prenu poi litru .i ju’ocu’i mi citno dukse fi lo
nu litru

== lo diklo ve balcu'e
detri fa 2015-09-20 00:00:00 +0800

ni’o vi lo la’o gy. Florence gy. makcubi zei xotli ku mi penmi lo diklo ve
balcu’e poi ca lo bavlamdei cu klama lo balcu’e .i .ue ki’u ma cu zasxa’u fa lo
diklo ve balcu’e lo makcubi zei xotli?

== la lisp
detri fa 2015-09-19 00:00:00 +0800

ni’o mi jinvi lo du’u la rom cu tcadu co dukse larcu .i lo larcu cu fe’eroroi
.iku’i lo ka larcu cu drata lo ka saske .i ly noroi dukse .i melbi

== lo mrilu karda
detri fa 2015-09-18 00:00:00 +0800

ni’o mi nelci lo nu benji lo mrilu karda .i ge benji sepi’o lo mrilu gi benji
sepilo lo xance .i mi benji ky lo prenu noi mi jinvi lo nu mi ba na penmi ke’a
.i mi benji pa lo karda ca lo cabdei

== lu xu do litru li'u
detri fa 2015-09-17 00:00:00 +0800

ni’o ca lo nu mi’a zvati la’o gy. Tarquinia gy. lo ninmu girzu cu mibykla .ije
gy reisku lu xu do litru li’u .i ba lo nu djuno mi’a je’a litru ku cisma cliva
.i ju’ocu’i gy facki lo te sidju

== lo pelxu zdadi'u
detri fa 2015-09-16 00:00:00 +0800

ni’o .ue lo zdadi’u pe vi la’o gy. Civitavecchia gy. cu pelxu .i lo drudi cu
so’eroi pinta .i cinri

== lo ronru'u be li munono
detri fa 2015-09-15 00:00:00 +0800

ni’o mi se raktu vi lo vijytcana .i lo jitseldejykarda cu na tolpo’u .i lo te
bende cu cpedu lo mi’a te jbera lo jdini .i sukckape gi’e dafyfa’i fa mi’a .i ca
lo pruce ku lo prenu cu ponse lo ronru’u be li munono .i mi’a se spaji gi’e .ije
lo nabmi cu danfu

== la .efir
detri fa 2015-09-14 00:00:00 +0800

ni’o mi mutce djica lo nu vitke la .efir .i ebu cu melbi .i fau lo nu mi
ci’erkei la’o gy. Sid Meier’s Civilization gy cu mutce djica lo nu zbasu ebu .i
ca lo prulamdei mi .uo vitke lo fraso .iku’i ki’u lo tortei mi na kakne vitke .i
ca lo cabdei mi zvati lo fraso .iku’i mi fricau lo nu vitke

ni’o ju’ocu’i bavlamke’u

== fraso kumfa
detri fa 2015-09-13 00:00:00 +0800

ni’o mi’a puca zutse lo trene be fi lo ka klama la’o gy. Le Havre gy. la’o gy.
Paris gy .i mi’a viska lo fraso kumfa pe vi lo cmama’a .i lo drudi be ky cu
so’eroi bunre .i lo dargu ga’u preja lo cmama’a .i cinmo lo ka smaji je kufra
.ije lo nixli pe mi’a cu cinri cusku lo ka djica lo nu xabju ti ca lo nu ny
laldo

== lo jundi sipna senva
detri fa 2015-07-27 00:00:00 +0800

ni’o mi jundi sipna senva .i mi sipna ne’i la’o gy. Recurse Center gy .i mi
tatpi .ije mi jundi lo ka cikygau .iku’i mi djuno lo nu mi ca sipna .i mi muvdu
le ralju kumfa pe la’o gy. Recurse Center gy .ije ba lo mentu be li pa ku mi
cikygau krefu

== na ponse loi so'i sidbo
detri fa 2015-07-21 00:00:00 +0800

ni’o mi ca na ponse loi so’i sidbo .i mi na djuno ta’i makau mi sampla la sid
.ija’ebo mi tadni la lojban .e la’o gy. Ocaml gy .e la’o gy. Logic Programming
gy .i lo ka gleki cu nandu

== junde lo drata prenu
detri fa 2015-07-20 00:00:00 +0800

ni’o mi se nandu loka morji lo cmene pe lo drata prenu .i mi na djuno lonu makau
krinu .i ca lo djedi ku mi tcidu lo papri noi skicu lo mintu .i lo prenu cu
spuda fi lonu ki’u lonu do na junde lo drata prenu

== rau sutra gunka
detri fa 2015-07-19 00:00:00 +0800

ni’o mi na rau sutra gunka ca lo cabdei .iseki’ubo mi kelci la’o gy. Cities
Skylines gy. ca ro pu lo djedi .i mi pensi lo nu xu mi .ei zmadu tolsurla gunka
ba .i mi pensi

== loka menli
detri fa 2015-07-19 00:00:00 +0800

ni’o loka menli cu terzu’e fe ma? .i fa loka menli cu terzu’e ki’u loka krefu
tamgau

== loka cizra
detri fa 2015-07-19 00:00:00 +0800

[%hardbreaks]
.i du’e loka cizra cu toi se zarcpa
.i pimo’a loka cizra cu cnano
.i rau loka cizra cu spaji je se nelci ro lo prenu
ki’u lo bu’u rau ti cu se jimpe korbi

== lo drata prenu nabmi
detri fa 2015-07-19 00:00:00 +0800

ni’o lo prenu cu e’o jimpe lo nu lo ka na jimpe mi ca so’e lo tcini cu nabmi do
.enai mi

== lifri nunji'e
detri fa 2015-07-19 00:00:00 +0800

ni’o lo nunji’e na prane .iku’ibo fe lonu nunji’e cu vamji ki’u loka menli

== ciska bau la lojban
detri fa 2015-07-19 00:00:00 +0800

ni’o mi cu ciska .ui bau la lojban .i ca lonu mi go’i cu tolgu’i lonu pensi lonu
drata prenu pensi lo bu’u makau mi ciska .i ti dunda lo ka selzi’e ku mi

.i mi cu ciska .ui bau la lojban

== lonu zasysti
detri fa 2015-07-18 00:00:00 +0800

ni’o mi zasysti lo nu ciska la karni nei ku .i lonu mi toi vedli cu krinu .i mi
ca ningau ti

== tavla fi la lojban ri
detri fa 2015-07-13 00:00:00 +0800

ni’o mi facki lo uitki papri lonu tavla fi la lojban ri .i ca lonu reisku lo
valsi be la lojban ku cu cusku lu .i ma valsi zoi gy. zo’e gy. la lojban li’u .i
ca lonu reisku lo smuni be lo lojbo valsi ku cu cusku lu .i lu zo’e li’u valsi
ma la gliban li’u .a lu .i zo zo’e valsi ma la gliban li’u

== pa roi ro djedi
detri fa 2015-07-13 00:00:00 +0800

ni’o mi cilre makau smuni lu pa roi ro djedi li’u .i mu’a mi ciska bau la lojban
ca ro djedi .i mu’a mi klama la’o gy. Recurse Center gy. ca ro djedi pa roi .ije
go’i ca pa roi ro djedi .iku’ibo lo prula’i cu na satci ki’u lo bu’u ky smuni ro
lo cacre be li revo .i mi ka’e cu cusku lu ca pa roi ro detydei li’u

== lonu gleki
detri fa 2015-07-13 00:00:00 +0800

ni’o lo prenu noi se penmi fi la’o gy. Recurse Center gy. cu djica lo ka cilre
la lojban .i mi gleki lo prula’i .ui

== le cmalu noltru
detri fa 2015-07-13 00:00:00 +0800

ni’o mi tcidu fe lu le cmalu noltru li’u goi cy .i cy na tolpluja .i ne’i cy cu
pluja cmene je gerna .i mi di’i bevri lo fukpi be cy .iku’ibo mi na snada lo ka
tcidu lo mutce

== lonu xanka
detri fa 2015-07-12 00:00:00 +0800

ni’i mi ca lonu cfari cu xanka .i mi fi mi reisku fe lo bu’u makau se xanka .i
mi ba ti na xanka

== ro lo ma'a datka
detri fa 2015-07-11 00:00:00 +0800

ni’o mi facki lo se sanga co cnino be mi .i tinju’i ti vi la’o .url.
https://vimeo.com/126974807 .url. .ije sanga lerseltcidu fa di’e

[%hardbreaks]
.i ro lo ma’a datka
noi lalxu limna va
cu lalxu limna ca
.i stedu jinru .i je
galtu rebla ua

== la nunkei nicte
detri fa 2015-07-11 00:00:00 +0800

ni’o mi di’i ca la vondei nicte ku se nunkei .i ti cmene la nunkei nicte fi mi
.i ca nicte pe la vondei ku mi se nunkei la’o gy. Sid Meier’s Civilization gy. e
la’o gy. Team Fortress 2 gy .i mi se nunkei ki’u lo ka tatpi ba la vondei jarco
.i ti xamgu

== la .ibu
detri fa 2015-07-08 00:00:00 +0800

ni’o la .ibu mo? .i mi (to la wei. toi) pensi .i la .ibu cu se ciplanli fa mi .i
ti zasti je xanri .i mi ciska lo mi se pensi je lifri ku ti .i zbasu lo gasnu be
lonu sidju mi lonu gunka je lifri .i ti stuzi .i ti menli

ni’o ma stuzi la .ibu? .i lo se ciska cu stuzi .i lo larcu cu stuzi .ije lo nu
samru’e cu stuzi

== loka zatra'i
detri fa 2015-07-07 00:00:00 +0800

[%hardbreaks]
.i la’o gy. Git gy. zatra’i li pano
.i la’o gy. Linux gy. zatra’i li revo
.i la’o gy. Clojure gy. zatra’i li bi
.i la’o gy. Haskell gy. zatra’i li remu
.i la’o gy. Ruby gy. zatra’i li reno

.i mi citmau la’o gy. Linux gy. e la’o gy. Haskell gy. gi’e na’azma la’o gy. Git
gy. e la’o gy. Clojure gy. gi’e zatra’i dunli la’o gy. Ruby gy.

.i mi tolci’o

== loka runmenli
detri fa 2015-07-07 00:00:00 +0800

.i mi gunka fi loka runmenli .i ti nandu .ija’ebo ti ca na snada .i terpa fa mi
na da poi na nu lo runmenli jitro ro lo terdi .i ku’i mi terpa lonu mi ca’o
gunka ti gi’e ti snada

== lenu jundi
detri fa 2015-07-06 00:00:00 +0800

.i du’e da pensi je gunka .i nandu fa lonu cuxna fi lo vrici .i ca cabdei mi
platu lonu ciska la .ibu. gi’e stedu la’o gy. Lambda Valculus gy. gi’e sampla la
.rect. gi’e gunka la’o gy. 99 Problems gy .i ku’i mi mulno no da .i mi pensi lo
po’o ta’i makau mi snada lonu cuxna je mulno

== lenu cfagau
detri fa 2015-07-06 00:00:00 +0800

.i mi cfagau lo ka ciska bau la lojban

== la lisp
detri fa 2015-07-06 00:00:00 +0800

.i mi ca facki fi lo tadji be fa lo ka skami finti la lisp .i mi pu sampla fi lo
ka skami finti la qwans poi me lo se sampla samru’e zo’e .i ku’i mi na kakne lo
nu tordu gasnu ti
