= lo se pensi
Wei Tang <wei@that.world>

[meta=description]
ni'o mi pensi je ciska lo se pensi be mi .i di'e du ti

== sampu
detri fa 2015-11-10 00:00:00 +0800

ni’o lo ka sampu cu vajni .i ri se smuni lo ka frili fa lo ka cusku gi’e jimpe
.i lo tcidu cu kakne lo nu frili jimpe lo se cusku pe lo ka sampu ta’i po’o lo
pe’anai se cusku .i va’i lo tcidu cu kakne lo nu frili jimpe secau lo na’e se
cusku .iku’i pau xu lo tordu se cusku pe lo sampu cu mulno

ni’o lo se cusku ku secau lo drata datni cu lacri lo ka pu zasti kei selju’o
ciste pe lo tcidu lo nu jimpe .i va’o lo nu lo tcidu cu jimpe gi’e cy cu ke
cmalu ficybi’o kei je ke barda xlura ku mi’a smudu’a cy lo ka sampu

ni’o tezu’e lo nu cusku lo sampu ku so’o lo selsnu cu se cusku .i pamai .i lo ka
pu zasti kei selju’o ciste ku cu .ei cusku .i remai .i lo mutce xlura cu .ei
cusku .i cimai .i lo ka sampu cu cusku

== lo litru se stidi pe lo skami prenu
detri fa 2015-10-23 00:00:00 +0800

ni’o di’e cu litru se stidi .ila’a do pu cilre di’e ca lo nu do verba .iku’i
sa’u do pu na go’i

1. ko dafyfa’i lo nu ta’i makau cu citka gi’e sipna gi’e lo nu klama .i la’e di’u na so’eroi nandu .i ta’i citka fa lo sutra cidja gusta nagi’a do nonkansa litru .i ta’i sipna fa lo nu kibro ternupcpe .i ta’i klama fa lo nu pamoi troci lo gubni bevgundi gi’e remoi troci lo taksi
2. ko cpedu fi lo gusta nagi’a do na kakne lo nu sispe’i lo vimstizu
3. ko vricykricru
4. ko retsku fi lo diklo
5. do zdifri nagi’a litru klama lo stuzi poi na remgunma lo litru
6. lo laldo ke litru tadji cu xamgu
7. ko zvasisku lo slabu nagi’a cnino tcini
8. ko zvasisku lo pendo ckaji prenu nagi’a terpa lo nu retsku
9. ko troci lo nu se carvrama’e
10. ko troci lo nu cadzu .iku’i ko na cadzu lo clani vi lo tcadu
11. ko terve’u lo diklo selbeifonxa karda .i ti sidju ckaji

== ciska bau la lojban
detri fa 2015-10-12 00:00:00 +0800

ni’o mi ca muvgau lo mi se ciska pe bau lo glibau ku lo jbobau .i ki’u ma mi
muvgau lo sorselpli lo narsorselpli .i mi gasnu ti ki’unai no krinu .i mi go’i
ki’u lo so’o vanji krinu po’u di’e

ni’o la lojban cu se baupli lo se dubjavme’a lo kilto .i ti nibyti’i lo nu do na
lakne penmi lo drata lojbo prenu fau lo nu do cadzu lo klaji pe vi lo plini .i
ti dunda do lo ka zifre .i do ciska bau la lojban secau lo nu xanka lo nu lo
cunso prenu cu tcidu lo se ciska gi’e jmisre ti gi’e pensi lo du’u do bebna .i
do zifre ciska

ni’o ku’i lo se ciska be do cu jimpe se kakne lo prenu poi baupli la lojban .i
po’o prenu poi baupli la lojban .i na lojbo fanva minji .i ti sabji lo kambandu
fo la’e prula’i jufmei

== tu'a le nu litru
detri fa 2015-10-11 00:00:00 +0800

ni’o mi cmizu’e la’o gy. Semester at Sea gy. co’a lo detri be li 2015 pi’e 9
mo’u lo detri be li 2015 pi’e 12 .i mi mutce litru ca ti .i mi peisku lo du’u
vajni lo nu mi jimpe le smuni be lo nu litru

ni’o lo nu litru cu na frili .i ti pluja .i ti tatpi .i do platu lo du’u makau
cu se gunka do .ije do platu lo du’u makau cu farna .i do nu’o farna cirko .i do
nu’o tolclite .i vajni fa lo nu do nu’o senpi lo du’u ki’u makau ku do litru .i
simsa lo nu mi’o senpi lo smuni be lo nu jmive 

== glico gi'i lojbo
detri fa 2015-10-11 00:00:00 +0800

ni’o ca lo nu mi ciska ku lo se ciska cu se bangu lo glibau gi’i jbobau .i le se
retsku cu vajni fi lo nu mi ponse re lo kibro zvati ku .e lo nu glico fa lo pa
moi gi’e lojbo fa lo re moi

ni’o mi ciska bau lo glibau mu’i lo nu mi jikca .i mi gasnu fi lo nu mi tavla lo
drata .iseki’ubo mi ciska tu’a skami bau lo glibau

ni’o mi ciska bau lo jbobau mu’i lo nu mi pensi .i mi gasnu fi lo nu mi vreji
ciska lo se pensi gi’e klina pensi .iseki’ubo mi ciska tu’a se pensi .e tu’a se
karni .e tu’a pemci

== kamtemci bavmu'iske
detri fa 2015-09-20 00:00:00 +0800

ni’o smudu’a loi bavykriske lo ka ckaji lo ka saske gi’e ckaji lo ka krici tu’a
lo balvi .i loi bavykriske cu pilno la bavykriske tadji .i pau ma dukti loi
bavykriske .i ra na velcki .i loi velcki cu dukti loi sakse .iseba’ibo loi krici
cu dukti loi mukti .iseki’ubo loi bavykri cu dukti loi bavmu’i .i loi bavykriske
cu dukti loi bavmu’iske po’u loi pijyske

ni’o su’o lo bavmu’iske cu ckaji lo to’e ka temci .i ra tolkamtemci bavmu’iske
.i ki’u lo du’u by na ka temci ku friti fa lo nu jimpe .i loi tolkamtemci
bavmu’iske se klesi loi selmarde .i mu’a tolkamtemci bavmu’iske fa lo selmarde
be lo du’u sisku roda poi ckaji lo ka jetnu gi’e jungau fi roda poi ckaji lo ka
jetnu .iku’i so’ida cu srera .i pamai srera lo ka dunli kei ranji po’u lo
kamdunra’i .i da fliba nagi’a paroi tarti lo ka na marde .i remai srera lo ka
tolju’i temci .i roda poi jmive cu canci ca lo djedi

ni’o drata ckaji lo ka temci .i ri kamtemci bavmu’iske .i finti lo ka temci kei
termonsi’o .i mu’a kamtemci kavmu’iske fa lo nu mulno lo ka sisku roda poi ckaji
lo ka jetnu gi’e jungau fi ro da poi ckaji lo ka jetnu .i lo ka kamtemci
bavmu’iske cu morna lo ka lisri .i larcu nagi’a melbi lisri

ni’o lo melbi bavmu’i cu larcu .ija’o lo du’u lo ka saske cu larcu cu cumki
